### PR TITLE
Fixes iOS detection

### PR DESCRIPTION
**Pull request by brunobg**
The previous code returned true in Android devices.

### CODE REVIEW

**Comment by plika** [comment]
LGTM but wondering why `Apple` is not sufficient.

**Comment by brunobg** [comment]
"Apple" appears in the user agent of Chrome Android.

**Comment by obastemur** [comment]
@brunobg ping! this PR needs an update

**Comment by brunobg** [comment]
What exactly is needed from me? I don't have write access to your repo. It also seems that the conflict came from accepting https://github.com/jxcore/jxm/pull/27 first, no?

**Comment by obastemur** [comment]
You are invited as a contributor, please check your email. Thanks

**Comment by brunobg** [comment]
Sorry, I couldn't solve the conflict, so I commited the fix. https://github.com/jxcore/jxm/commit/99d1b66919b5f1843d163c2fe8d2b9cb394aa06d

Closing this.

**Comment by obastemur** [comment]
Okay thanks

**Pull request closed without merging**
