### PR TITLE
When sending to server, url does not depend on script src any more

### PR DESCRIPTION
**Pull request by karaxuna**

### CODE REVIEW

**Comment by ktrzeciaknubisa** [comment]
Let me see into this and make some tests.

**Comment by ktrzeciaknubisa** [comment]
Ok, I think that's a good start. However I have some comments :)

1. Maybe it's better to determine http/https protocol from client's request (not server's settings). This is because once you'll configure jxm for SSL use it starts two servers (HTTP and HTTPS). Now client can use one of them (can be non-SSL too). That's why `SocketURL` is determined this way (in *_server_handler.js*, 2 lines below your change). However it does so at client's side, but it also could be checked by server from client's request.

2.  We can use same `cnn.req.headers.host` for `SocketURL`, too.

I think they both can go now this way:

```js
cnn.res.write(ns + ".ListenHost = (document.location.protocol == 'https:') ? 'https://" + cnn.req.headers.host + "' : 'http://" + cnn.req.headers.host + "';");
cnn.res.write(ns + ".SocketURL = (document.location.protocol == 'https:') ? 'wss://" + cnn.req.headers.host + "' : 'ws://" + cnn.req.headers.host + "';");
```
It's just a proposal. Waiting for your opinion :)

**Comment by karaxuna** [comment]
If jxcore server is run on http and host is https, then ListenUrl will be https and it will fail. So best option will be to determine protocol from request I think. I'll make changes if you agree

**Comment by ktrzeciaknubisa** [comment]
> If jxcore server is run on http and host is https, then ListenUrl will be https and it will fail.

Do you mean server http and client connection attempt by https? Well, client will not be even able to connect, I guess.

> I'll make changes if you agree

Sure :)

**Comment by ktrzeciaknubisa** [comment]
BTW. We can also get rid of `getScriptOrigin()`. This is not even part of API. It was introduced very recently and was supposed to behave like a private method.

**Comment by karaxuna** [comment]
@ktrzeciaknubisa I have changed logic: If jxcore server uses SSL, let the protocol be same as the protocol of referrer. If jxcore uses only non ssl, then force protocol to be http. I put protocol in ListenProtocol variable. See latest commit

**Comment by ktrzeciaknubisa** [comment]
Thanks, I think this works exactly as it should.

**Pull request merged**
